// 本地地名词典：中文行政区划 / 城市 → 英文标准译名。
// 全部为静态本地数据，不调用任何翻译 API。

/** 直辖市与特别行政区（完整名，避免被拆成「北京 + 市」）。 */
const MUNICIPALITIES: Record<string, string> = {
  北京: "Beijing",
  北京市: "Beijing",
  上海: "Shanghai",
  上海市: "Shanghai",
  天津: "Tianjin",
  天津市: "Tianjin",
  重庆: "Chongqing",
  重庆市: "Chongqing",
  香港: "Hong Kong, China",
  香港特别行政区: "Hong Kong, China",
  澳门: "Macao, China",
  澳门特别行政区: "Macao, China",
};

/** 省、自治区（含完整名）。 */
const PROVINCES: Record<string, string> = {
  广东: "Guangdong",
  广东省: "Guangdong Province",
  广西: "Guangxi",
  广西壮族自治区: "Guangxi Zhuang Autonomous Region",
  江苏: "Jiangsu",
  江苏省: "Jiangsu Province",
  浙江: "Zhejiang",
  浙江省: "Zhejiang Province",
  山东: "Shandong",
  山东省: "Shandong Province",
  四川: "Sichuan",
  四川省: "Sichuan Province",
  湖南: "Hunan",
  湖南省: "Hunan Province",
  湖北: "Hubei",
  湖北省: "Hubei Province",
  河南: "Henan",
  河南省: "Henan Province",
  河北: "Hebei",
  河北省: "Hebei Province",
  福建: "Fujian",
  福建省: "Fujian Province",
  江西: "Jiangxi",
  江西省: "Jiangxi Province",
  安徽: "Anhui",
  安徽省: "Anhui Province",
  云南: "Yunnan",
  云南省: "Yunnan Province",
  贵州: "Guizhou",
  贵州省: "Guizhou Province",
  海南: "Hainan",
  海南省: "Hainan Province",
  山西: "Shanxi",
  山西省: "Shanxi Province",
  陕西: "Shaanxi",
  陕西省: "Shaanxi Province",
  甘肃: "Gansu",
  甘肃省: "Gansu Province",
  青海: "Qinghai",
  青海省: "Qinghai Province",
  辽宁: "Liaoning",
  辽宁省: "Liaoning Province",
  吉林: "Jilin",
  吉林省: "Jilin Province",
  黑龙江: "Heilongjiang",
  黑龙江省: "Heilongjiang Province",
  台湾: "Taiwan, China",
  台湾省: "Taiwan, China",
  内蒙古: "Inner Mongolia",
  内蒙古自治区: "Inner Mongolia Autonomous Region",
  新疆: "Xinjiang",
  新疆维吾尔自治区: "Xinjiang Uyghur Autonomous Region",
  西藏: "Tibet",
  西藏自治区: "Tibet Autonomous Region",
  宁夏: "Ningxia",
  宁夏回族自治区: "Ningxia Hui Autonomous Region",
};

/** 主要城市（裸名，不含「市」；「市」由行政区划后缀统一处理为 City）。 */
const CITIES: Record<string, string> = {
  广州: "Guangzhou",
  深圳: "Shenzhen",
  杭州: "Hangzhou",
  南京: "Nanjing",
  成都: "Chengdu",
  武汉: "Wuhan",
  西安: "Xi'an",
  沈阳: "Shenyang",
  青岛: "Qingdao",
  厦门: "Xiamen",
  苏州: "Suzhou",
  宁波: "Ningbo",
  大连: "Dalian",
  长沙: "Changsha",
  郑州: "Zhengzhou",
  济南: "Jinan",
  哈尔滨: "Harbin",
  长春: "Changchun",
  昆明: "Kunming",
  南宁: "Nanning",
  福州: "Fuzhou",
  合肥: "Hefei",
  南昌: "Nanchang",
  贵阳: "Guiyang",
  兰州: "Lanzhou",
  太原: "Taiyuan",
  石家庄: "Shijiazhuang",
  乌鲁木齐: "Urumqi",
  呼和浩特: "Hohhot",
  西宁: "Xining",
  银川: "Yinchuan",
  拉萨: "Lhasa",
  海口: "Haikou",
  三亚: "Sanya",
  珠海: "Zhuhai",
  佛山: "Foshan",
  东莞: "Dongguan",
  无锡: "Wuxi",
  常州: "Changzhou",
  温州: "Wenzhou",
  绍兴: "Shaoxing",
  嘉兴: "Jiaxing",
  金华: "Jinhua",
  台州: "Taizhou",
  泉州: "Quanzhou",
  烟台: "Yantai",
  威海: "Weihai",
  潍坊: "Weifang",
  淄博: "Zibo",
  洛阳: "Luoyang",
  开封: "Kaifeng",
  南阳: "Nanyang",
  唐山: "Tangshan",
  保定: "Baoding",
  邯郸: "Handan",
  鞍山: "Anshan",
  抚顺: "Fushun",
  吉林市: "Jilin City",
  大庆: "Daqing",
  包头: "Baotou",
  鄂尔多斯: "Ordos",
  咸阳: "Xianyang",
  宝鸡: "Baoji",
  天水: "Tianshui",
  桂林: "Guilin",
  丽江: "Lijiang",
  大理: "Dali",
  张家界: "Zhangjiajie",
};

/** 合并后的完整地名表（用于最长匹配）。 */
export const PLACES: Record<string, string> = {
  ...MUNICIPALITIES,
  ...PROVINCES,
  ...CITIES,
};

/** 行政区划 / 道路后缀词（用于地址转写）。 */
export const REGION_SUFFIX: Record<string, string> = {
  自治区: "Autonomous Region",
  自治州: "Autonomous Prefecture",
  特别行政区: "Special Administrative Region",
  街道: "Subdistrict",
  大道: "Avenue",
  开发区: "Development Zone",
  高新区: "High-tech Zone",
  新区: "New District",
  地区: "Prefecture",
  省: "Province",
  市: "City",
  区: "District",
  县: "County",
  镇: "Town",
  乡: "Township",
  村: "Village",
  路: "Road",
  街: "Street",
  巷: "Lane",
  弄: "Alley",
  号: "No.",
  栋: "Building",
  幢: "Building",
  单元: "Unit",
  室: "Room",
  楼: "Building",
  层: "Floor",
  门: "Gate",
  组: "Group",
  旗: "Banner",
  盟: "League",
};
