import type { DocumentDefinition } from "@/lib/types";
import { GENDER, NATIONALITY, BIRTH_CERT_TYPE } from "@/lib/dictionaries";

export const birthCertificate: DocumentDefinition = {
  type: "birth-certificate",
  titleZh: "出生证明",
  titleEn: "Birth Certificate",
  descriptionZh: "适用于未成年人、家庭关系证明。",
  pdfTitleEn: "Birth Certificate",
  // 出生医学证明 → 动态标题
  dynamicPdfTitle: (values) => {
    return values["certType"] === "出生医学证明" ? "Medical Certificate of Birth" : "Birth Certificate";
  },
  pdfSubtitleEn: "Translation of Birth Certificate (出生证明)",
  headerNote:
    "This is an English translation prepared for reference. The original Chinese document remains the authoritative record.",
  fileName: "Birth-Certificate-Translation",
  kind: "translation",
  sections: [
    {
      id: "type",
      labelZh: "证件类型",
      labelEn: "Certificate Type",
      fields: [
        {
          id: "certType",
          labelZh: "证件类型",
          labelEn: "Certificate Type",
          type: "select",
          options: BIRTH_CERT_TYPE,
          translationMode: "fixed",
        },
      ],
    },
    {
      id: "newborn",
      labelZh: "新生儿信息",
      labelEn: "Newborn Information",
      fields: [
        {
          id: "newbornName",
          labelZh: "新生儿姓名",
          labelEn: "Newborn's Name",
          type: "text",
          translationMode: "manual",
          autoTranslate: "name",
          hint: "输入中文姓名将自动转为拼音，可手动修改为护照英文名。",
        },
        {
          id: "gender",
          labelZh: "性别",
          labelEn: "Gender",
          type: "select",
          options: GENDER,
          translationMode: "fixed",
        },
        {
          id: "birthDate",
          labelZh: "出生日期",
          labelEn: "Date of Birth",
          type: "date",
          translationMode: "none",
        },
        {
          id: "birthTime",
          labelZh: "出生时间",
          labelEn: "Time of Birth",
          type: "text",
          translationMode: "none",
          hint: "例如：14:30。",
        },
        {
          id: "birthPlace",
          labelZh: "出生地点",
          labelEn: "Place of Birth",
          type: "text",
          translationMode: "manual",
          autoTranslate: "address",
          fullWidth: true,
        },
        {
          id: "gestationWeeks",
          labelZh: "孕周",
          labelEn: "Gestational Age",
          type: "text",
          translationMode: "manual",
          hint: "例如：39 周 → 39 weeks。",
        },
        {
          id: "weight",
          labelZh: "体重（g）",
          labelEn: "Birth Weight (g)",
          type: "number",
          translationMode: "none",
          inputMode: "numeric",
        },
        {
          id: "height",
          labelZh: "身长（cm）",
          labelEn: "Birth Length (cm)",
          type: "number",
          translationMode: "none",
          inputMode: "numeric",
        },
      ],
    },
    {
      id: "mother",
      labelZh: "母亲信息",
      labelEn: "Mother's Information",
      fields: [
        {
          id: "motherName",
          labelZh: "母亲姓名",
          labelEn: "Mother's Name",
          type: "text",
          translationMode: "manual",
          autoTranslate: "name",
        },
        {
          id: "motherAge",
          labelZh: "母亲年龄",
          labelEn: "Mother's Age",
          type: "number",
          translationMode: "none",
          inputMode: "numeric",
        },
        {
          id: "motherNationality",
          labelZh: "母亲国籍",
          labelEn: "Mother's Nationality",
          type: "select",
          options: NATIONALITY,
          translationMode: "fixed",
        },
        {
          id: "motherIdNumber",
          labelZh: "母亲身份证号",
          labelEn: "Mother's ID Number",
          type: "text",
          translationMode: "none",
          hint: "证件号码仅在本地处理，不进行联网校验。",
        },
      ],
    },
    {
      id: "father",
      labelZh: "父亲信息",
      labelEn: "Father's Information",
      fields: [
        {
          id: "fatherName",
          labelZh: "父亲姓名",
          labelEn: "Father's Name",
          type: "text",
          translationMode: "manual",
          autoTranslate: "name",
        },
        {
          id: "fatherAge",
          labelZh: "父亲年龄",
          labelEn: "Father's Age",
          type: "number",
          translationMode: "none",
          inputMode: "numeric",
        },
        {
          id: "fatherNationality",
          labelZh: "父亲国籍",
          labelEn: "Father's Nationality",
          type: "select",
          options: NATIONALITY,
          translationMode: "fixed",
        },
        {
          id: "fatherIdNumber",
          labelZh: "父亲身份证号",
          labelEn: "Father's ID Number",
          type: "text",
          translationMode: "none",
          hint: "证件号码仅在本地处理，不进行联网校验。",
        },
      ],
    },
    {
      id: "issuance",
      labelZh: "签发信息",
      labelEn: "Issuance Information",
      fields: [
        {
          id: "issuingAuthority",
          labelZh: "签发机构",
          labelEn: "Issuing Authority",
          type: "text",
          translationMode: "manual",
          fullWidth: true,
        },
        {
          id: "issueDate",
          labelZh: "签发日期",
          labelEn: "Date of Issue",
          type: "date",
          translationMode: "none",
        },
      ],
    },
  ],
};
