import type { DocumentDefinition } from "@/lib/types";
import {
  OWNERSHIP_TYPE,
  PROPERTY_RIGHT_TYPE,
  PROPERTY_RIGHT_NATURE,
  PROPERTY_USE,
} from "@/lib/dictionaries";

export const propertyCertificate: DocumentDefinition = {
  type: "property-certificate",
  titleZh: "房产证 / 不动产权证",
  titleEn: "Property Certificate",
  descriptionZh: "适用于资产及国内约束证明。",
  pdfTitleEn: "Real Estate Ownership Certificate",
  pdfSubtitleEn: "Translation of Property Certificate (房产证 / 不动产权证)",
  headerNote:
    "This is an English translation prepared for reference. The original Chinese document remains the authoritative record.",
  fileName: "Property-Certificate-Translation",
  kind: "translation",
  sections: [
    {
      id: "type",
      labelZh: "证件类型",
      labelEn: "Certificate Type",
      fields: [
        {
          id: "certType",
          labelZh: "证件类型",
          labelEn: "Certificate Type",
          type: "select",
          options: [
            { value: "不动产权证书", labelZh: "不动产权证书", labelEn: "Real Estate Certificate" },
            { value: "房屋所有权证", labelZh: "房屋所有权证", labelEn: "House Ownership Certificate" },
          ],
          translationMode: "fixed",
        },
      ],
    },
    {
      id: "basic",
      labelZh: "基本信息",
      labelEn: "Basic Information",
      fields: [
        {
          id: "rightsHolder",
          labelZh: "权利人",
          labelEn: "Rights Holder",
          type: "text",
          translationMode: "manual",
          autoTranslate: "name",
          hint: "输入中文姓名将自动转为拼音，可手动修改为护照英文名。",
        },
        {
          id: "coOwnership",
          labelZh: "共有情况",
          labelEn: "Co-ownership",
          type: "select",
          options: OWNERSHIP_TYPE,
          translationMode: "fixed",
        },
        {
          id: "location",
          labelZh: "坐落",
          labelEn: "Location",
          type: "textarea",
          translationMode: "manual",
          autoTranslate: "address",
          fullWidth: true,
          hint: "输入中文地址将自动转写为英文，可手动修改。",
        },
        {
          id: "unitNumber",
          labelZh: "不动产单元号",
          labelEn: "Real Estate Unit Number",
          type: "text",
          translationMode: "none",
        },
      ],
    },
    {
      id: "rights",
      labelZh: "权利信息",
      labelEn: "Rights Information",
      fields: [
        {
          id: "rightType",
          labelZh: "权利类型",
          labelEn: "Type of Right",
          type: "select",
          options: PROPERTY_RIGHT_TYPE,
          translationMode: "fixed",
        },
        {
          id: "rightNature",
          labelZh: "权利性质",
          labelEn: "Nature of Right",
          type: "select",
          options: PROPERTY_RIGHT_NATURE,
          translationMode: "fixed",
        },
        {
          id: "use",
          labelZh: "用途",
          labelEn: "Use",
          type: "select",
          options: PROPERTY_USE,
          translationMode: "fixed",
        },
        {
          id: "area",
          labelZh: "面积",
          labelEn: "Area",
          type: "text",
          translationMode: "manual",
          hint: "例如：89.5 ㎡ → 89.5 m²。",
        },
        {
          id: "useTerm",
          labelZh: "使用期限",
          labelEn: "Term of Use",
          type: "text",
          translationMode: "manual",
          hint: "例如：2015-01-01 至 2085-01-01 → 1 January 2015 to 1 January 2085。",
        },
        {
          id: "otherConditions",
          labelZh: "其他状况",
          labelEn: "Other Conditions",
          type: "textarea",
          translationMode: "manual",
          fullWidth: true,
        },
      ],
    },
    {
      id: "registration",
      labelZh: "登记信息",
      labelEn: "Registration Information",
      fields: [
        {
          id: "registrationAuthority",
          labelZh: "登记机构",
          labelEn: "Registration Authority",
          type: "text",
          translationMode: "manual",
          fullWidth: true,
        },
        {
          id: "registrationDate",
          labelZh: "登记日期",
          labelEn: "Date of Registration",
          type: "date",
          translationMode: "none",
        },
        {
          id: "certificateNumber",
          labelZh: "证书编号",
          labelEn: "Certificate Number",
          type: "text",
          translationMode: "none",
        },
      ],
    },
  ],
};
